# ----------------------------
# Makefile Options
# ----------------------------

NAME = ArdUSB
ICON = icon.png
DESCRIPTION = "TI-84 Plus CE Messaging App"
COMPRESSED = YES
COMPRESSED_MODE = zx0

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz
EXCLUDE_DIRS = .vscode
ARCHIVED = YES

# ----------------------------

include $(shell cedev-config --makefile)
