# ----------------------------
# Makefile Options
# ----------------------------

NAME = Graphx
ICON = icon.png
DESCRIPTION = "Arduino USB Test"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
